import Head from "next/head";
import Header from "./../Header/Header"
import Footer from "./../Footer/Footer"

const MainLayoutComponent = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link
          rel="icon"
          href="/images/278574815_5083230241754989_1219310810229563917_n.jpg"
        /> */}
      </Head>
      <Header />
      {/* <main>{children}</main> */}
      {children}
      {/* <footer> */}
        <Footer />
      {/* </footer> */}
    </>
  );
};

export default MainLayoutComponent;
