import Head from "next/head";
import Header from "./../Header/Header";
import Footer from "./../Footer/Footer";

const MainLayoutComponent = ({ title, children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
};

export default MainLayoutComponent;
