import React from "react";
import Head from "next/head";
import Sidebar from "../components/Sidebar/Sidebar";
import Topnav from "../components/Topnav/Topnav";
export default function MainLayout({ children }) {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Sidebar />
      <div className="main">
        <div className="main__content">
          <Topnav />
          {children}
        </div>
      </div>
    </>
  );
}
